apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    version: blue  // For the green deployment, the selector (Ideally the LB) should point to green deploymeny manifest
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
